### ISSUE TITLE
Decompiling not working

### ISSUE THREAD

**Issue by aha-181** [LucasFaudman/apkscan#1]
I've installed apkscan according to the 'From Source Install Commands' instructions. When trying to scan an example apk with the basic usage command `apkscan AndroGoat.apk` I get the following error while decompiling:  **ERROR - Incorrect arguments: File not found /usr/share/jadx/bin/AndroGoat.apk** and no decompiled files are generated.

jadx is installed in `/usr/bin/jadx`

The full console output is:
```
┌──(.venv)─(mobile㉿mobile)-[~/Documents/apkscan]
└─$ apkscan AndroGoat.apk                
   ('-.      _ (`-. .-. .-')   .-')             ('-.         .-')
  ( OO ).-. ( (OO  )\  ( OO ) ( OO ).          ( OO ).-.    ( OO )
  / . --. /_.`     \,--. ,--.(_)---\_) .-----. / . --. /,--./ ,--,
  | \-.  \(__...--''|  .'   //    _ | '  .--./ | \-.  \ |   \ |  |
  | '  |  ||  /  | ||      / \  :` `. |  |('-. | '  |  ||    \|  |
  | |_.'  ||  |_.' ||     '   '..`''. |  |OO  )| |_.'  ||  .     |
  |  .-.  ||  .___.'|  .   \ .-._)   \|  |`-'| |  .-.  ||  |\    |
  |  | |  ||  |     |  |\   \\       /'  '--'\ |  | |  ||  | \   |
  `--' `--'`--'     `--' '--' `-----'  `-----' `--' `--'`--'  `--'                                                             
  APKscan v0.3.0 - Scan for secrets, endpoints, and other sensitive data                                                       
  after decompiling and deobfuscating Android files.                                                                           
  (.apk, .xapk, .dex, .jar, .class, .smali, .zip, .aar, .arsc, .aab, .jadx.kts)                                                
                                                                                                                               
  (c) Lucas Faudman, 2024. License information in LICENSE file.                                                                
  Credits to the original authors of all dependencies used in this project.

Starting APKscan...

No decompiler binaries specified. Defaulting to JADX binary at /usr/bin/jadx.
Found jadx binary: /usr/bin/jadx

Loading secret locators from 1 files.

Loaded 224 secret locators.

Initialized Decompiler:
- Decompiler:(binary_paths={'jadx': PosixPath('/usr/bin/jadx')}, extra_args={'jadx': []}, deobfuscate=True, output_suffix=-decompiled, working_dir=/home/mobile/Documents/apkscan, remove_failed_output_dirs=False, concurrent_executor=CuncurrentExecutor(concurrency_type=thread, results_order=completed, max_workers=None, chunksize=1, timeout=None, shutdown=True, wait=True, cancel_pending=False, executor=None, executor_init_kwargs={}))

Initialized Secret Scanner:
- SecretScanner(secret_locators=224, concurrent_executor=CuncurrentExecutor(concurrency_type=process, results_order=completed, max_workers=None, chunksize=1, timeout=None, shutdown=True, wait=True, cancel_pending=False, executor=None, executor_init_kwargs={})))

Decompiler Binaries:
- /usr/bin/jadx

Secret Locator Files:
- /home/mobile/Documents/apkscan/src/apkscan/secret_locators/default.json

Output File:
- /home/mobile/Documents/apkscan/secrets_output.json


Decompiling started at 09:22:46:46S

Creating output directory: /home/mobile/Documents/apkscan/AndroGoat-decompiled
Output directory created: /home/mobile/Documents/apkscan/AndroGoat-decompiled
Running jadx on AndroGoat.apk
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
ERROR - Incorrect arguments: File not found /usr/share/jadx/bin/AndroGoat.apk
Successfully decompiled AndroGoat.apk with jadx

Indexing decompiled files in /home/mobile/Documents/apkscan/AndroGoat-decompiled/jadx...
Found 0 decompiled files for AndroGoat.apk
Status: COMPLETE | Decompiled: 1/1 (100.000000%) | 

Decompiling COMPLETE. Decompiled 1 files with 1 errors. Elapsed time: 0:00:03.293299

Status: COMPLETE | Decompiled: 1/1 (100.000000%) | 
Found 0 new secrets (0 unique).
Decompiled 1 files with 1 errors in 0:00:03.293299.
Scanned 0 files and found 0 secrets in None.
Total Elapsed time: 0:00:03.299032

Output written to secrets_output.json

APKscan done. No secrets found. 
```

**Comment by LucasFaudman** [comment]
Hey @aha-181, thanks for providing the full output it makes fixing this significantly easier.

It looks like the issue is that `JADX` is interpreting the relative path to your APK incorrectly. It's trying to decompile the file at `/usr/share/jadx/bin/AndroGoat.apk` which is clearly not the correct path.  

I'll see if it is caused by how `JADX` handles relative paths, or if it's a bug somewhere else in APKscan, then push a patch accordingly.

If you have time please try to see if it works when you use the absolute path of your APK instead of the relative path. This will help me determine if there is another issue involved. 

If you have not moved the file:
`apkscan /home/mobile/Documents/apkscan/AndroGoat.apk`
OR 
```apkscan `realpath AndroGoat.apk` ```

**Comment by LucasFaudman** [comment]
@aha-181 Please see if [this update](https://github.com/LucasFaudman/apkscan/pull/2/commits/4b1b37f8b871ad5fc942203d221cbcb5969ed528) fixes it for you. 

As far as I can tell the issue was that `JADX` was interpreting a relative path argument as being in `/usr/share/jadx/bin/`, not in the directory `apkscan` is run from.  The reason is most likely differences in relative path handling with certain jadx version + OS combinations.

[This update](https://github.com/LucasFaudman/apkscan/pull/2/commits/4b1b37f8b871ad5fc942203d221cbcb5969ed528) ensures that input files are resolved to their absolute path(s) before being yielded to the decompiler processes so all decompiler binaries will now receive the absolute paths as arguments, and any differences in relative path handling should no longer matter.

I was unable to reproduce the issue when testing on OSX, Ubuntu and Kali however, so if it persists for you after updating, please let me know and I will reopen this issue. (If it does, please provide the output of `jadx --version` so I can test with your version.

Thanks again!

**Comment by aha-181** [comment]
Hi Lucas

Thanks so much for the fast response. The update fixed my issue. The jadx version that I use is _1.4.7_ and I'm using it on Kali Linux _Linux version 6.6.15-amd64 (devel@kali.org) (gcc-13 (Debian 13.2.0-13) 13.2.0, GNU ld (GNU Binutils for Debian) 2.42) #1 SMP PREEMPT_DYNAMIC Kali 6.6.15-2kali1 (2024-04-09)_

Thanks again for the fast fix and looking forward to using the tool.

**Comment by LucasFaudman** [comment]
@aha-181 No problem, thanks for helping me identify the issue! 

I tested with 1.5.0 and 1.4.5 and could not reproduce, so it's Interesting that it happened with 1.47, but either way I'm glad it's working now.
